# Generated by Django 5.2.4 on 2025-08-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionTags',
            new_name='TransactionTag',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'verbose_name_plural': 'Transaction Categories'},
        ),
        migrations.AlterModelOptions(
            name='transactiontag',
            options={'verbose_name_plural': 'Transaction Tags'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
